# Generated by Django 6.0 on 2026-01-16 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#0D7377', help_text='Hex color code (e.g., #FF6B6B)', max_length=7)),
                ('amount', models.DecimalField(decimal_places=10, default=0, help_text='Exact recurring amount (high precision for conversions)', max_digits=20)),
                ('amount_display', models.DecimalField(decimal_places=2, default=0, help_text='Rounded amount for display (2 decimal places)', max_digits=12)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly (Every 2 weeks)'), ('4-week', '4-Week (Every 28 days)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (Every 3 months)'), ('yearly', 'Yearly')], default='monthly', help_text='How often to allocate the recurring amount', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pockets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Budget category for organizing pockets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pockets', to='api.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=10, default=0, help_text='Exact amount allocated to this item', max_digits=20)),
                ('amount_display', models.DecimalField(decimal_places=2, default=0, help_text='Rounded amount for display (2 decimal places)', max_digits=12)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly (Every 2 weeks)'), ('4-week', '4-Week (Every 28 days)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (Every 3 months)'), ('yearly', 'Yearly')], default='monthly', help_text='How often this item expense occurs', max_length=10)),
                ('is_other', models.BooleanField(default=False, help_text='Whether this is the auto-generated "Other" item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pocket', models.ForeignKey(help_text='The pocket this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.pocket')),
            ],
            options={
                'ordering': ['is_other', 'created_at'],
            },
        ),
    ]
