# Generated by Django 6.0 on 2026-01-20 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['is_other', 'is_percentage', 'created_at']},
        ),
        migrations.AddField(
            model_name='item',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='percentage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount_display',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly (Every 2 weeks)'), ('4-week', '4-Week (Every 28 days)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (Every 3 months)'), ('yearly', 'Yearly'), ('percentage', 'Percentage')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='pocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.pocket'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='amount_display',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pockets', to='api.category'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='color',
            field=models.CharField(default='#0D7377', max_length=7),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly (Every 2 weeks)'), ('4-week', '4-Week (Every 28 days)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (Every 3 months)'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
