# Generated by Django 6.0 on 2026-01-10 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pocket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pocket',
            name='color',
            field=models.CharField(default='#0D7377', help_text='Hex color code (e.g., #FF6B6B)', max_length=7),
        ),
        migrations.AddField(
            model_name='pocket',
            name='frequency',
            field=models.CharField(choices=[('none', 'No recurring amount'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly (Every 2 weeks)'), ('monthly', 'Monthly')], default='none', help_text='How often to allocate the recurring amount', max_length=10),
        ),
        migrations.AddField(
            model_name='pocket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recurring amount to allocate to this pocket', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pocket',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Budget category for organizing pockets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pockets', to='api.category'),
        ),
    ]
