# Generated by Django 6.0 on 2026-01-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_options_item_is_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='due_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly (Every 2 weeks)'), ('4-week', '4-Week (Every 28 days)'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('percentage', 'Ratio')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly (Every 2 weeks)'), ('4-week', '4-Week (Every 28 days)'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
