# Generated by Django 6.0 on 2026-01-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pocket_options_pocket_color_pocket_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recurring amount to allocate to this pocket', max_digits=10),
        ),
    ]
