# Generated by Django 6.0 on 2026-01-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pocket_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount allocated to this item', max_digits=10)),
                ('is_other', models.BooleanField(default=False, help_text='Whether this is the auto-generated "Other" item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pocket', models.ForeignKey(help_text='The pocket this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.pocket')),
            ],
            options={
                'ordering': ['is_other', 'created_at'],
            },
        ),
    ]
