# Generated by Django 6.0 on 2026-01-24 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_incomesortinstance_sortedpocket_sorteditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortedpocket',
            name='sort_instance',
        ),
        migrations.CreateModel(
            name='SortedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorted_incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sorted Income',
                'verbose_name_plural': 'Sorted Incomes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sortedpocket',
            name='sorted_income',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sorted_pockets', to='api.sortedincome'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IncomeSortInstance',
        ),
    ]
