# Generated by Django 6.0 on 2026-01-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortedincome',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
